### PR TITLE
bhl_ripstation_utils January 2019 Update

### PR DESCRIPTION
**Pull request by hyeeyoungkim**
This pull request includes:

- New: `check_output_structure.py` can validate audio (.wav) and video (.mp4) files using FFmpeg's -f null method
- New: `check_os_files.py` (previously `check_thumbs_db_ds_store.py`) can target addtional operating system files, `Desktop DB` and `Desktop DF`
- Improvement: `check_output_structure.py` and `check_os_files.py` incldues addtional parameters to turn off functions
- Improvement: `check_output_structure.py` provides an execution time message
- Improvement: `check_os_files.py` asks for user's confirmation before deleting files
- Various bug fixes

`README.md` has been also updated to reflect the changes. The scripts have been tested with large CD-based assessions on Windows, Python 3.7.2.

### CODE REVIEW

**Comment by djpillen** [comment]
Just to make sure we're following standard conventions and that we don't run into any issues adding additional parameters in the future, would it be possible to make sure that all arguments follow the [GNU Program Argument Syntax Conventions](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html) for the use of single/double hyphens for short (i.e., single character) and long options? Some of the arguments as they are currently formulated could be interpreted as multiple short options, e.g. -src could be read as equivalent to -s -r -c, -ds could be read as equivalent to -d -s, etc.

**Comment by hyeeyoungkim** [comment]
@djpillen Thanks for pointing out the parameter issue. I'll check the convention document and update the parameters.

**Comment by hyeeyoungkim** [comment]
@djpillen I updated `argparse` argument names for all scripts.

**Comment by djpillen** [comment]
Looks good, thanks!

**Pull request merged**
